---
deployment:
  tasks:
    - export DEPLOYPATH_CORE=/home2/omnispac/omnishop-core/

    - /bin/mkdir -p $DEPLOYPATH_CORE

    # Deploy backend code to omnishop-core
    - /bin/cp -R * $DEPLOYPATH_CORE
    - /bin/cp -f .env.production $DEPLOYPATH_CORE/.env

    # NOTE:
    # 1. Point your api-omni-shop.omnispace3d.com Document Root to /home2/omnispac/omnishop-core/public
    # 2. Run 'php artisan storage:link' in the omnishop-core directory on the server.
