<?php

return [
    'solarandstorage' => [
        'name'          => 'Solar and Storage Live Kenya 2026',
        'short_name'    => 'SSL Kenya 2026',
        'slug'          => 'solarandstorage',
        'dates'         => 'August 26–27, 2026',
        'venue'         => 'Kenyatta International Convention Centre (KICC), Nairobi, Kenya',
        'logo'          => '/static/images/ssl-kenya-logo.png',
        'contact_email' => 'solarandstoragelive@omnispace3d.com',
        'catalog_password_default' => 'ssl2026',
        'deadlines'     => [
            ['category' => 'Furniture, Audiovisual & Accessories', 'deadline' => 'August 15, 2026'],
            ['category' => 'Flooring (Basic)',                      'deadline' => 'August 20, 2026'],
            ['category' => 'Staffing & Services',                   'deadline' => 'August 14, 2026'],
            ['category' => 'Booth Branding (Standard)',             'deadline' => 'July 2, 2026'],
            ['category' => 'Booth Branding (Rush Orders)',          'deadline' => 'August 7, 2026'],
            ['category' => 'Custom Stand Builds',                   'deadline' => 'July 15, 2026'],
        ],
        'order_prefix'  => 'OMN-SSL2026',
    ],
    'gitex' => [
        'name'          => 'AI Everything Kenya × GITEX Kenya 2026',
        'short_name'    => 'GITEX Kenya 2026',
        'slug'          => 'gitex',
        'dates'         => 'May 19–21, 2026',
        'venue'         => 'Kenyatta International Convention Centre (KICC), Nairobi, Kenya',
        'logo'          => '/static/images/gitex-kenya-logo.png',
        'contact_email' => 'gitex@omnispace3d.com',
        'catalog_password_default' => 'gitex2026',
        'deadlines'     => [
            ['category' => 'Furniture, Audiovisual & Accessories', 'deadline' => 'May 9, 2026'],
            ['category' => 'Flooring (Basic)',                      'deadline' => 'May 14, 2026'],
            ['category' => 'Staffing & Services',                   'deadline' => 'May 8, 2026'],
            ['category' => 'Booth Branding (Standard)',             'deadline' => 'April 19, 2026'],
            ['category' => 'Booth Branding (Rush Orders)',          'deadline' => 'May 2, 2026'],
            ['category' => 'Custom Stand Builds',                   'deadline' => 'April 19, 2026'],
        ],
        'order_prefix'  => 'OMN-GITEX2026',
    ],
    'seamless' => [
        'name'          => 'Seamless East Africa 2026',
        'short_name'    => 'Seamless EA 2026',
        'slug'          => 'seamless',
        'dates'         => 'TBC 2026',
        'venue'         => 'TBC, Nairobi, Kenya',
        'logo'          => '/static/images/seamless-logo.png',
        'contact_email' => 'seamless@omnispace3d.com',
        'catalog_password_default' => 'seamless2026',
        'deadlines'     => [
            ['category' => 'Furniture, Audiovisual & Accessories', 'deadline' => 'TBC'],
            ['category' => 'Flooring (Basic)',                      'deadline' => 'TBC'],
            ['category' => 'Staffing & Services',                   'deadline' => 'TBC'],
            ['category' => 'Booth Branding (Standard)',             'deadline' => 'TBC'],
            ['category' => 'Booth Branding (Rush Orders)',          'deadline' => 'TBC'],
            ['category' => 'Custom Stand Builds',                   'deadline' => 'TBC'],
        ],
        'order_prefix'  => 'OMN-SEA2026',
    ],
];
